image: node:16-slim
stages:
  - publish
pages:
    stage: publish
    script:
        - mkdir -p public/
        - cp ./src/Application.html public
    artifacts:
        paths:
          - public
    rules:
      - if: $CI_COMMIT_BRANCH == 'main'
    environment:
        name: production/${CI_PROJECT_NAME}/${CI_COMMIT_REF_NAME}
