stages:
  - build
  - deploy

build:
  stage: build
  script:
    - tsc -p tsconfig.json
  artifacts:
    paths:
      - src/

deploy:
  stage: deploy
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public