stages:
  - publish
pages:
    stage: publish
    script:
        - tsc -p tsconfig.json
        
    artifacts:
        paths:
          - public
    environment:
        name: production/${CI_PROJECT_NAME}/${CI_COMMIT_REF_NAME}
